# Copy this file to config.yaml then replace the current values with your own

recipients:
  - name@domain.com

locations:
  - name: 'Bray Head'
    coords:
      latitude: 53.1909
      longitude: -6.0839
    info: weather  # Include weather forecast for this location

  - name: 'Bray seafront'
    coords:
      latitude: 53.2048
      longitude: -6.0979
    info: tide  # Include tide times for this location
